### ISSUE TITLE
Create route page

### ISSUE THREAD

**Issue by naomi-eliasar** [drikusroor/brazil-blog#56]
Create a route page that shows the route we will take

- It is a separate page, like the crew page, and has a button in the header
- On it there's a map of the route we're taking. Could be a google maps map, or something cuter
- It also displays on which days we will be at what place

**Comment by drikusroor** [comment]
See also here: https://brazil.kokokoding.nl/locations/itinerary/

(and of course the bar on top of the blog index page)
