### ISSUE TITLE
Wrong crew avatar shows

### ISSUE THREAD

**Issue by naomi-eliasar** [drikusroor/brazil-blog#66]
The wrong crew avatar shows on the crew members page
[
See video on google drive](https://drive.google.com/file/d/18aie_OEToRX1O6yi_uVgUNByRv9ZrkKP/view?usp=drive_link)

![wrong crew avatar](https://github.com/user-attachments/assets/8ece5b30-36a2-45b5-9c16-be4b3d12fc1f)

**Comment by drikusroor** [comment]
I think this is a duplicate or overlap of #60 - it shows you own user's avatar when you're logged in, rite?

**Comment by naomi-eliasar** [comment]
> I think this is a duplicate or overlap of #60 - it shows you own user's avatar when you're logged in, rite?

Yes it is. It's also fixed now by 60. I'll close this one
