### ISSUE TITLE
Cannot upload pictures from phone

### ISSUE THREAD

**Issue by naomi-eliasar** [drikusroor/brazil-blog#94]
It gives the error that the image is too big, eventhough it is less than 10mb

This happens both when trying to change the profile picture and when uploading an image in a blog post

After trying to upload a profile picture:
![IMG_2304](https://github.com/user-attachments/assets/9de026d4-0ec8-479f-9562-be6687750455)

When uploading an image in a blog post:
![IMG_2305](https://github.com/user-attachments/assets/4d535dec-1764-40df-bb3a-9208e1110a8f)

**Comment by drikusroor** [comment]
Should be fixed per dd8268bd274db3882218b7a2020dbdab3ed4a779
