### ISSUE TITLE
List of likes doesn't work very well and its styling is inconsistent

### ISSUE THREAD

**Issue by drikusroor** [drikusroor/brazil-blog#98]
The likes list only works when you hover over the number text and not when you hover over the icon.

Additionally, the borders and text colors look different for likes on posts and likes on comments:

<img width="224" alt="image" src="https://github.com/user-attachments/assets/4216ce17-8528-465f-a55e-5a0655cc740f">
<img width="121" alt="image" src="https://github.com/user-attachments/assets/2a300f34-3575-4cae-bfa9-e38bc21f3cea">

**Comment by naomi-eliasar** [comment]
Only seeing the list when hovering the number is a feature, not a bug. Because I thought that otherwise it would be annoying when you're trying to click to like, and the list shows up

**Comment by naomi-eliasar** [comment]
And the styling in the comments section being to the right instead of below, was also intentional. Because I thought it would be ugly if it overlapped the comment below it

**Comment by drikusroor** [comment]
> And the styling in the comments section being to the right instead of below, was also intentional. Because I thought it would be ugly if it overlapped the comment below it

I would display the list below the counter button
